"""add idempotency records

Revision ID: 129500974fc0
Revises: 5edc016cd71c
Create Date: 2026-05-31 14:59:04.852614
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "129500974fc0"
down_revision: Union[str, None] = "5edc016cd71c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=True),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "action", "key", "player_id", name="uq_idempotency_action_key_player"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("idempotency_records")
    # ### end Alembic commands ###
