"""add_city_game_day

Revision ID: 477f53e05e71
Revises: e6a0f98f6b10
Create Date: 2026-06-08 00:09:20.275036
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "477f53e05e71"
down_revision: str | None = "e6a0f98f6b10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cities", sa.Column("game_day", sa.Integer(), nullable=False, server_default="1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cities", "game_day")
    # ### end Alembic commands ###
