"""initial schema

Revision ID: 5edc016cd71c
Revises:
Create Date: 2026-05-31 14:32:04.756936
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "5edc016cd71c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("treasury_balance", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("tax_rate_income", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tax_rate_property", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("inflation_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("mayor_player_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "cartels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("industry_type", sa.String(length=50), nullable=False),
        sa.Column("lobby_fund", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("balance", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("mood", sa.Integer(), nullable=False),
        sa.Column("education_level", sa.String(length=50), nullable=False),
        sa.Column("diploma_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_foreign_key(
        "fk_cities_mayor_player_id",
        "cities",
        "players",
        ["mayor_player_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "transactions_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("sender_type", sa.String(length=20), nullable=False),
        sa.Column("receiver_id", sa.Uuid(), nullable=False),
        sa.Column("receiver_type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("tax_deducted", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("purpose", sa.String(length=100), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bank_loans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("principal_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("remaining_debt", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("daily_payment", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "businesses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("owner_player_id", sa.Uuid(), nullable=True),
        sa.Column("owner_share_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("cash_balance", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_player_id"], ["players.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_player_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("breed", sa.String(length=50), nullable=False),
        sa.Column("hunger", sa.Integer(), nullable=False),
        sa.Column("health", sa.Integer(), nullable=False),
        sa.Column("loyalty", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["owner_player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "police_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("offense_type", sa.String(length=100), nullable=False),
        sa.Column("fine_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sports_clubs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sport_type", sa.String(length=30), nullable=False),
        sa.Column("owner_player_id", sa.Uuid(), nullable=True),
        sa.Column("cash_balance", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("stadium_capacity", sa.Integer(), nullable=False),
        sa.Column("ticket_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("training_efficiency", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("league_points", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_player_id"], ["players.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "transports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("owner_player_id", sa.Uuid(), nullable=True),
        sa.Column("ticket_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("passenger_capacity", sa.Integer(), nullable=False),
        sa.Column("maintenance_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("operational_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_player_id"], ["players.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hostels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("room_number", sa.Integer(), nullable=False),
        sa.Column("rent_price_per_day", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("energy_regen_per_hour", sa.Integer(), nullable=False),
        sa.Column("tenant_player_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_player_id"], ["players.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_player_id"),
    )
    op.create_table(
        "insurance_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=True),
        sa.Column("provider_business_id", sa.Uuid(), nullable=False),
        sa.Column("coverage_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("daily_premium", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["provider_business_id"], ["businesses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("salary_per_hour", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("min_education", sa.String(length=50), nullable=False),
        sa.Column("energy_cost_per_shift", sa.Integer(), nullable=False),
        sa.Column("filled_by_player_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["filled_by_player_id"], ["players.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filled_by_player_id"),
    )
    op.create_table(
        "labor_unions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("strike_active", sa.Boolean(), nullable=False),
        sa.Column("strike_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id"),
    )
    op.create_table(
        "player_athlete_contracts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("club_id", sa.Uuid(), nullable=False),
        sa.Column("salary_per_match", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("contract_status", sa.String(length=20), nullable=False),
        sa.Column("strength_stat", sa.Integer(), nullable=False),
        sa.Column("stamina_stat", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["sports_clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_cities_mayor_player_id", "cities", type_="foreignkey")
    op.drop_table("player_athlete_contracts")
    op.drop_table("labor_unions")
    op.drop_table("jobs")
    op.drop_table("insurance_policies")
    op.drop_table("hostels")
    op.drop_table("transports")
    op.drop_table("sports_clubs")
    op.drop_table("police_records")
    op.drop_table("pets")
    op.drop_table("businesses")
    op.drop_table("bank_loans")
    op.drop_table("transactions_log")
    op.drop_table("players")
    op.drop_table("cartels")
    op.drop_table("cities")
    # ### end Alembic commands ###
