"""Add business management and city metrics models

Revision ID: 89a9e33d2101
Revises: b2c3d4e5f6a7
Create Date: 2026-06-07 20:17:29.306046
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "89a9e33d2101"
down_revision: str | None = "b2c3d4e5f6a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("businesses", sa.Column("management_mode", sa.String(length=20), nullable=True))
    op.add_column("businesses", sa.Column("business_size", sa.Integer(), nullable=True))
    op.add_column("businesses", sa.Column("ai_profit_rate", sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column("businesses", sa.Column("daily_revenue", sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column("businesses", sa.Column("is_startup", sa.Boolean(), nullable=True))
    op.add_column("businesses", sa.Column("startup_stage", sa.String(length=20), nullable=True))
    op.add_column("businesses", sa.Column("startup_funding", sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column("businesses", sa.Column("startup_investors", sa.JSON(), nullable=True))
    op.add_column("businesses", sa.Column("startup_success_chance", sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column("businesses", sa.Column("profit_margin", sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column("businesses", sa.Column("market_share", sa.Numeric(precision=5, scale=2), nullable=True))

    # Оновити існуючі записи значеннями за замовчуванням
    op.execute("UPDATE businesses SET management_mode = 'manual' WHERE management_mode IS NULL")
    op.execute("UPDATE businesses SET business_size = 1 WHERE business_size IS NULL")
    op.execute("UPDATE businesses SET ai_profit_rate = 0.10 WHERE ai_profit_rate IS NULL")
    op.execute("UPDATE businesses SET daily_revenue = 0.00 WHERE daily_revenue IS NULL")
    op.execute("UPDATE businesses SET is_startup = false WHERE is_startup IS NULL")
    op.execute("UPDATE businesses SET startup_stage = 'idea' WHERE startup_stage IS NULL")
    op.execute("UPDATE businesses SET startup_funding = 0.00 WHERE startup_funding IS NULL")
    op.execute("UPDATE businesses SET startup_investors = '{}' WHERE startup_investors IS NULL")
    op.execute("UPDATE businesses SET startup_success_chance = 60.00 WHERE startup_success_chance IS NULL")
    op.execute("UPDATE businesses SET profit_margin = 15.00 WHERE profit_margin IS NULL")
    op.execute("UPDATE businesses SET market_share = 1.00 WHERE market_share IS NULL")

    # Зробити стовпці NOT NULL
    op.alter_column("businesses", "management_mode", nullable=False)
    op.alter_column("businesses", "business_size", nullable=False)
    op.alter_column("businesses", "ai_profit_rate", nullable=False)
    op.alter_column("businesses", "daily_revenue", nullable=False)
    op.alter_column("businesses", "is_startup", nullable=False)
    op.alter_column("businesses", "startup_stage", nullable=False)
    op.alter_column("businesses", "startup_funding", nullable=False)
    op.alter_column("businesses", "startup_investors", nullable=False)
    op.alter_column("businesses", "startup_success_chance", nullable=False)
    op.alter_column("businesses", "profit_margin", nullable=False)
    op.alter_column("businesses", "market_share", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesses", "market_share")
    op.drop_column("businesses", "profit_margin")
    op.drop_column("businesses", "startup_success_chance")
    op.drop_column("businesses", "startup_investors")
    op.drop_column("businesses", "startup_funding")
    op.drop_column("businesses", "startup_stage")
    op.drop_column("businesses", "is_startup")
    op.drop_column("businesses", "daily_revenue")
    op.drop_column("businesses", "ai_profit_rate")
    op.drop_column("businesses", "business_size")
    op.drop_column("businesses", "management_mode")
    # ### end Alembic commands ###
