"""Add city metrics district prestige player interactions

Revision ID: e6a0f98f6b10
Revises: 89a9e33d2101
Create Date: 2026-06-07 21:42:25.387918
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e6a0f98f6b10"
down_revision: str | None = "89a9e33d2101"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("business_revenue_modifier", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("employment_modifier", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("crime_rate_modifier", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("affected_districts", sa.JSON(), nullable=False),
        sa.Column("affected_business_types", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "city_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("gdp_per_capita", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("unemployment_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("business_density", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("startup_success_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("average_business_profit", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("crime_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("happiness_index", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("education_level", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("social_mobility", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("infrastructure_quality", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("traffic_index", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("environmental_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("inflation_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("property_price_index", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("consumer_spending", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("city_id"),
    )
    op.create_table(
        "district_prestige",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("district_id", sa.Uuid(), nullable=False),
        sa.Column("business_friendly_rating", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tax_incentives", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("development_level", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("prestige_level", sa.Integer(), nullable=False),
        sa.Column("safety_rating", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("cultural_significance", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("transport_access", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("utility_quality", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("green_spaces", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("average_property_value", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("commercial_rent_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("foot_traffic_index", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["district_id"], ["city_districts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("district_id"),
    )
    op.create_table(
        "player_business_ratings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("total_businesses", sa.Integer(), nullable=False),
        sa.Column("successful_startups", sa.Integer(), nullable=False),
        sa.Column("failed_businesses", sa.Integer(), nullable=False),
        sa.Column("total_employees", sa.Integer(), nullable=False),
        sa.Column("business_reputation", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("influence_level", sa.Integer(), nullable=False),
        sa.Column("trust_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("city_contribution", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("employment_created", sa.Integer(), nullable=False),
        sa.Column("taxes_paid", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("total_investments", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("investment_returns", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("portfolio_value", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id"),
    )
    op.create_table(
        "player_interactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player1_id", sa.Uuid(), nullable=False),
        sa.Column("player2_id", sa.Uuid(), nullable=False),
        sa.Column("interaction_type", sa.String(length=20), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=True),
        sa.Column("impact_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("relationship_change", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("amount_involved", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(["player1_id"], ["players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player2_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_interactions")
    op.drop_table("player_business_ratings")
    op.drop_table("district_prestige")
    op.drop_table("city_metrics")
    op.drop_table("city_events")
    # ### end Alembic commands ###
